canvas = document.getElementById("mycanvas");
ctx=canvas.getContext("2d");
ctx.beginPath();
ctx.strokeStyle=red;
ctx.lineWidth=1;
ctx.arc(150,143,430,200 * Math.PI);
ctx.stroke();
canvas = document.getElementById("mycanvas");
ctx=canvas.getContext("2d");
ctx.beginPath();
ctx.strokeStyle=blue;
ctx.lineWidth=5;
ctx.arc(150,143,430,200 * Math.PI);
ctx.stroke();
canvas = document.getElementById("mycanvas");
ctx=canvas.getContext("2d");
ctx.beginPath();
ctx.strokeStyle=black;
ctx.lineWidth=1;
ctx.arc(150,143,430,200 * Math.PI);
ctx.stroke();
canvas = document.getElementById("mycanvas");
ctx=canvas.getContext("2d");
ctx.beginPath();
ctx.strokeStyle=blue;
ctx.lineWidth=5;
ctx.arc(150,143,430,200 * Math.PI);
ctx.stroke();
canvas = document.getElementById("mycanvas");
ctx=canvas.getContext("2d");
ctx.beginPath();
ctx.strokeStyle=red;
ctx.lineWidth=1;
ctx.arc(150,143,430,200 * Math.PI);
ctx.stroke();
canvas = document.getElementById("mycanvas");
ctx=canvas.getContext("2d");
ctx.beginPath();
ctx.strokeStyle=blue;
ctx.lineWidth=5;
ctx.arc(150,143,430,200 * Math.PI);
ctx.stroke();
canvas = document.getElementById("mycanvas");
ctx=canvas.getContext("2d");
ctx.beginPath();
ctx.strokeStyle=red;
ctx.lineWidth=1;
ctx.arc(150,143,430,200 * Math.PI);
ctx.stroke();